name: tests
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: r-board
                    POSTGRES_PASSWORD: secret
                ports:
                    - 13338:5432
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        strategy:
            matrix:
                node-version: [15.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              uses: cypress-io/github-action@v2
              with:
                  runTests: false
            - name: Run unit tests
              run: yarn test:unit
            - name: Wait for DB
              run: yarn wait-for-db
            - name: Run integration tests
              run: yarn test:integration
            - name: Build
              run: yarn build
            - name: Run cypress tests
              uses: cypress-io/github-action@v2
              with:
                  install: false
                  start: yarn start
                  wait-on: "http://localhost:1337"
            - name: Prepare Playwright
              run: npx playwright install chromium
            - name: Run playwright tests
              run: yarn test:playwright
